name: Build macOS App

on:
  push:
    branches: [ "hotfix/video-conversion-fix" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install PyInstaller
        
    - name: Create icon
      run: |
        python make_icns.py
        iconutil -c icns icon.iconset
        
    - name: Build app
      run: |
        python -m PyInstaller "WebP Converter Mac.spec"
        
    - name: Create DMG
      run: |
        hdiutil create -volname "WebP Converter" -srcfolder "dist/WebP Converter.app" -ov -format UDZO "dist/WebP-Converter-macOS.dmg"
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: WebP-Converter-macOS
        path: dist/WebP-Converter-macOS.dmg
