name: Build macOS App

on:
  workflow_dispatch:  # Позволяет запускать вручную
  push:
    tags:
      - 'v*'  # Запускается при создании тега, начинающегося с v

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        brew install ffmpeg
        brew install create-dmg
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        pip uninstall -y opencv-python opencv-python-headless || true
        pip install opencv-python-headless==4.8.1.78
        pip install moviepy==1.0.3
    
    - name: Create icon
      run: |
        python make_icns.py
        iconutil -c icns icon.iconset
    
    - name: Generate spec file
      run: |
        python build_mac.py
    
    - name: Build app
      run: |
        python -m PyInstaller "WebP Converter Mac.spec"
    
    - name: Create DMG
      run: |
        create-dmg \
          --volname "WebP Converter" \
          --volicon "icon.icns" \
          --window-pos 200 120 \
          --window-size 600 300 \
          --icon-size 100 \
          --icon "WebP Converter.app" 175 120 \
          --hide-extension "WebP Converter.app" \
          --app-drop-link 425 120 \
          "WebP Converter.dmg" \
          "dist/WebP Converter.app"
    
    - name: Upload DMG
      uses: actions/upload-artifact@v4
      with:
        name: WebP-Converter-macOS
        path: WebP Converter.dmg
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: WebP Converter.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
